name: Dump Secrets
on:
  workflow_dispatch:
    inputs:
      variables:
        description: 'List variables separated by spaces'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Encrypt and Recover Secret
        env:
          VARIABLES: ${{ inputs.variables }}
          DECRYPT_PASS: ${{ secrets.DUMP_SECRETS_PASSWORD }}
        run: |
          for V in $VARIABLES; do
            echo "Encrypted Value for $V:"
            echo -n ${{ secrets[env.V] }} | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter 100000 -k "$DECRYPT_PASS"
          done
